package busybuilders;
import java.text.ParseException;
import javax.swing.*;
import java.util.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author botto
 */
public class frmIMSApp extends javax.swing.JFrame {

    
    //Global Reference to IMSAppController Object
    IMSAppController core = null;
    
    /**
     * Creates new form frmIMSApp
     */
    public frmIMSApp() {
        initComponents();
        core = new IMSAppController();
        
        core.loadSuppliers();
        core.loadInventory();
        core.loadEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        belPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtAInvID = new javax.swing.JTextField();
        txtAInvName = new javax.swing.JTextField();
        txtAInvCat = new javax.swing.JTextField();
        txtAInvUC = new javax.swing.JTextField();
        txtAInvRL = new javax.swing.JTextField();
        txtAInvSL = new javax.swing.JTextField();
        txtAInvQ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAInvData = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnViewInv = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInventoryDetails = new javax.swing.JTextPane();
        btnClearInv = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSupID = new javax.swing.JTextField();
        txtSupName = new javax.swing.JTextField();
        txtSupContact = new javax.swing.JTextField();
        txtSupCredit = new javax.swing.JTextField();
        btnASupData = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnViewSup = new javax.swing.JButton();
        btnSupClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSupplierDetails = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtStxID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtStxEmployeeAddedBy = new javax.swing.JTextField();
        txtStxTotal = new javax.swing.JTextField();
        btnAStxData = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtStxItem = new javax.swing.JTextField();
        txtStxDate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        btnManViewInv = new javax.swing.JButton();
        btnManClearInv = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taManInventoryDetails = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        btnManViewSup = new javax.swing.JButton();
        btnManCLearSup = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taManSupplierDetails = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Busy Builders");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Inventory Management System");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane2.setForeground(new java.awt.Color(0, 102, 102));

        txtAInvUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAInvUCActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel4.setText("Category");

        jLabel5.setText("Unit Cost");

        jLabel6.setText("Reorder Level");

        jLabel7.setText("Stock Level");

        jLabel9.setText("Quantity");

        btnAInvData.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnAInvData.setText("Save");
        btnAInvData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAInvDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAInvData, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAInvQ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtAInvSL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAInvRL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAInvUC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAInvCat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAInvName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAInvID, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(136, 136, 136))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAInvID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAInvName))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAInvCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAInvUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAInvRL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAInvSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAInvQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAInvData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Inventory", jPanel3);

        btnViewInv.setLabel("View All Inventory");
        btnViewInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInvActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(taInventoryDetails);

        btnClearInv.setLabel("Clear");
        btnClearInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewInv, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnClearInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnViewInv, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnClearInv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Updated Inventory", jPanel4);

        jLabel12.setText("ID");

        jLabel13.setText("Name");

        jLabel14.setText("Contact");

        jLabel15.setText("Credit");

        btnASupData.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnASupData.setText("Save");
        btnASupData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnASupDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnASupData, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txtSupID)
                    .addComponent(txtSupName)
                    .addComponent(txtSupContact)
                    .addComponent(txtSupCredit, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnASupData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Supplier", jPanel5);

        btnViewSup.setLabel("View Suppliers");
        btnViewSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSupActionPerformed(evt);
            }
        });

        btnSupClear.setLabel("Clear");
        btnSupClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupClearActionPerformed(evt);
            }
        });

        taSupplierDetails.setColumns(20);
        taSupplierDetails.setRows(5);
        jScrollPane2.setViewportView(taSupplierDetails);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewSup, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(btnSupClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnViewSup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSupClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Updated Suppliers", jPanel6);

        jLabel3.setText("Transaction ID");

        jLabel16.setText("Sales Date");

        jLabel17.setText("Added By");

        jLabel18.setText("Transaction Total");

        btnAStxData.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnAStxData.setText("Save");
        btnAStxData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAStxDataActionPerformed(evt);
            }
        });

        jLabel19.setText("Sales Items");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAStxData, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(txtStxID)
                    .addComponent(txtStxEmployeeAddedBy)
                    .addComponent(txtStxTotal)
                    .addComponent(txtStxItem)
                    .addComponent(txtStxDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStxID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtStxDate))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStxEmployeeAddedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAStxData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jLabel3.getAccessibleContext().setAccessibleName("");

        jTabbedPane2.addTab("Record Sales Transaction", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Sales Rep", jPanel1);

        btnManViewInv.setText("View All Inventory");
        btnManViewInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManViewInvActionPerformed(evt);
            }
        });

        btnManClearInv.setText("Clear");
        btnManClearInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManClearInvActionPerformed(evt);
            }
        });

        taManInventoryDetails.setColumns(20);
        taManInventoryDetails.setRows(5);
        jScrollPane4.setViewportView(taManInventoryDetails);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManViewInv, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(btnManClearInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnManViewInv, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnManClearInv, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("View All Inventory", jPanel9);

        btnManViewSup.setText("View All Suppliers");
        btnManViewSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManViewSupActionPerformed(evt);
            }
        });

        btnManCLearSup.setText("Clear");
        btnManCLearSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManCLearSupActionPerformed(evt);
            }
        });

        taManSupplierDetails.setColumns(20);
        taManSupplierDetails.setRows(5);
        jScrollPane3.setViewportView(taManSupplierDetails);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManViewSup, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManCLearSup, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnManViewSup, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManCLearSup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("View All Suppliers", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane6.getAccessibleContext().setAccessibleName("View Reports");
        jTabbedPane6.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Manager", jPanel2);

        javax.swing.GroupLayout belPanelLayout = new javax.swing.GroupLayout(belPanel);
        belPanel.setLayout(belPanelLayout);
        belPanelLayout.setHorizontalGroup(
            belPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, belPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        belPanelLayout.setVerticalGroup(
            belPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, belPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(belPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(belPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //save button on add inventory sales rep tab
    private void btnAInvDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAInvDataActionPerformed
        String emptyFields = "";  //to check mandatory fields

        // 1. Retrieve form data
        int id = Integer.parseInt(this.txtAInvID.getText());
        String n = this.txtAInvName.getText();
        //String de = this.txtAInvDesc.getText();
        String c = this.txtAInvCat.getText();
        Double uc = Double.parseDouble(this.txtAInvUC.getText());
        int rl = Integer.parseInt(this.txtAInvRL.getText());
        int sl = Integer.parseInt(this.txtAInvSL.getText());
        //Supplier sup = Supplier.parseSupplier(this.txtAInvSup.getText());
        int q = Integer.parseInt(this.txtAInvQ.getText());
        
        
        

        //int, string, string, double, int, int, supplier, int
        
        
        // 2.1 If Form data is valid 
        try{
        
        // 2. Validate form data
            if((n.trim()).equals("")){ //check name field
                emptyFields += "\nName";
            }
            if((c.trim()).equals("")){ //check category field
                emptyFields += "\nCategory";
            }  
            if(emptyFields.equals("")){       
        
        // 2.1 If Form data is valid 
        // - call save Student in Controller class passing the data

        
        boolean saved = core.saveInventoryData(id, n, c, uc, rl, sl, q);  
                    
                    
                // 2.1.1 Display feedback message to user
                    if(saved){
                           JOptionPane.showMessageDialog(
                                   null, 
                                   "Inventory Item Saved Successfully",
                                   "Message",
                                   JOptionPane.INFORMATION_MESSAGE);
                           
                           
                            
                           //clear form
                           this.txtAInvID.setText("");
                           this.txtAInvName.setText("");
                           this.txtAInvCat.setText("");
                           this.txtAInvUC.setText("");
                           this.txtAInvRL.setText("");
                           this.txtAInvSL.setText("");
                           //this.txtAInvSup.setText("");
                           this.txtAInvQ.setText("");
                           //this.txtAInvDesc.setText("");
                           
                           
                           
                       }else{
                           JOptionPane.showMessageDialog(
                                   null, 
                                   "Unable to Save Inventory Item.\n"
                                 + "Contact Support.",
                                   "Error",
                                   JOptionPane.ERROR_MESSAGE);
                    }
          
        }else{
                emptyFields = "The following fields require input.\n" +
                                emptyFields;
                
                throw new IMSException(emptyFields);
            }
    
    }
        catch(IMSException sise){
            JOptionPane.showMessageDialog(
                            null, 
                            sise.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(
                            null, 
                            ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
        }
        // 2.2 If Form data is invalid
        // - Display feedback msg to user
    }//GEN-LAST:event_btnAInvDataActionPerformed

  
    //save button on sales rep add supplier 
    private void btnASupDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnASupDataActionPerformed
        String emptyFields = "";  //to check mandatory fields


        // 1. Retrieve form data
        int id = Integer.parseInt(this.txtSupID.getText());
        String n = this.txtSupName.getText();
        String co = this.txtSupContact.getText();
        Double cr = Double.parseDouble(this.txtSupCredit.getText());
        
        
        
        boolean saved = core.saveSupplierData(id, n, co, cr);
        
        try{
        
        // 2. Validate form data
            if((n.trim()).equals("")){ //check lastname field
                emptyFields += "\nName";
            }
            if((co.trim()).equals("")){ //check firstname field
                emptyFields += "\nPhone";
            }
            if(emptyFields.equals("")){       
        
        // 2.1 If Form data is valid 
        // - call save Student in Controller class passing the data

        
        
                // 2.1.1 Display feedback message to user
                    if(saved){
                           JOptionPane.showMessageDialog(
                                   null, 
                                   "Supplier Saved Successfully",
                                   "Message",
                                   JOptionPane.INFORMATION_MESSAGE);
                           
                           
                            
                           //clear form
                           this.txtSupID.setText("");
                           this.txtSupName.setText("");
                           this.txtSupContact.setText("");
                           this.txtSupCredit.setText("");
                           
                           
                           
                       }else{
                           JOptionPane.showMessageDialog(
                                   null, 
                                   "Unable to Save Supplier.\n"
                                 + "Contact Support.",
                                   "Error",
                                   JOptionPane.ERROR_MESSAGE);
                    }
          
        }else{
                emptyFields = "The following fields require input.\n" +
                                emptyFields;
                
                
                throw new IMSException (emptyFields);
                //throw new IMSException(emptyFields);
            }
            
        }
             catch(IMSException sise){
            JOptionPane.showMessageDialog(
                            null, 
                            sise.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(
                            null, 
                            ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }  
        
    }//GEN-LAST:event_btnASupDataActionPerformed

        
        
    private void btnViewInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInvActionPerformed
            this.taInventoryDetails.setText("");

            //ArrayList<Inventory> progL = new ArrayList<Programme>();
            ArrayList<Inventory> InvL = new ArrayList<Inventory>();
            InvL = core.getIList();
            String results = ""; //initialize string to empty data
            
            
            for(int i=0; i < InvL.size(); i++){
            //append data into the result string
            results += (InvL.get(i)).toString();
        }
            
            this.taInventoryDetails.setText(results);
            
    }//GEN-LAST:event_btnViewInvActionPerformed

    
    /*
    private void txtAInvUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAInvUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAInvUCActionPerformed
*/
    
    
    private void btnAStxDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAStxDataActionPerformed



// 1. Retrieve form data
        int txID = Integer.parseInt(this.txtStxID.getText());
        //Date salesDate = this.txtStxDate.getTargetDate();
        ArrayList<Inventory> SalesItems = new ArrayList<Inventory>();
        Double txTotal = Double.parseDouble(this.txtStxTotal.getText());
        //int txID, Date salesDate, ArrayList<Inventory>, double txTotal
        //Date salesDate = Date.parseDate(this.txtStxDate.getDateFormatString());
        
        
        
        
        
        //initialize date to null
        Date salesDate = null;
        
        
        try {
            salesDate = new SimpleDateFormat("dd/MM/yyyy").parse(this.txtStxDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frmIMSApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        // 2. Save Programme Data
        boolean saved = core.saveTransactionData(txID, SalesItems, txTotal, salesDate);
        
        if(saved){
                JOptionPane.showMessageDialog(
                        null, 
                        "Transaction Saved Successfully",
                        "Message",
                        JOptionPane.INFORMATION_MESSAGE);
                
                //clear form
                this.txtStxID.setText("");
                this.txtStxDate.setText("");
                this.txtStxItem.setText("");
                this.txtStxEmployeeAddedBy.setText("");
                this.txtStxTotal.setText("");

                
            }else{
                JOptionPane.showMessageDialog(
                        null, 
                        "Unable to Save Transaction.\n"
                      + "Contact Support.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnAStxDataActionPerformed

    
    
    private void btnViewSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSupActionPerformed

            //ArrayList<Inventory> progL = new ArrayList<Programme>();
            ArrayList<Supplier> SupL = new ArrayList<Supplier>();
            SupL = core.getSList();
            String results = ""; //initialize string to empty data
            
            
            for(int i=0; i < SupL.size(); i++){
            //append data into the result string
            results += (SupL.get(i)).toString();
        }
            
            this.taSupplierDetails.setText(results);
    }//GEN-LAST:event_btnViewSupActionPerformed

    private void btnSupClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupClearActionPerformed
            this.taSupplierDetails.setText("");
    }//GEN-LAST:event_btnSupClearActionPerformed

    private void btnClearInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearInvActionPerformed
        this.taInventoryDetails.setText("");
    }//GEN-LAST:event_btnClearInvActionPerformed

    private void btnManViewInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManViewInvActionPerformed
            this.taManInventoryDetails.setText("");

            //ArrayList<Inventory> progL = new ArrayList<Programme>();
            ArrayList<Inventory> InvL = new ArrayList<Inventory>();
            InvL = core.getIList();
            String results = ""; //initialize string to empty data
            
            
            for(int i=0; i < InvL.size(); i++){
            //append data into the result string
            results += (InvL.get(i)).toString();
        }
            
            this.taManInventoryDetails.setText(results);
    }//GEN-LAST:event_btnManViewInvActionPerformed

    private void btnManCLearSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManCLearSupActionPerformed
            this.taManSupplierDetails.setText("");
    }//GEN-LAST:event_btnManCLearSupActionPerformed

    private void btnManClearInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManClearInvActionPerformed
        this.taManInventoryDetails.setText("");
    }//GEN-LAST:event_btnManClearInvActionPerformed

    private void btnManViewSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManViewSupActionPerformed
            this.taManSupplierDetails.setText("");

            //ArrayList<Inventory> progL = new ArrayList<Programme>();
            ArrayList<Supplier> SupL = new ArrayList<Supplier>();
            SupL = core.getSList();
            String results = ""; //initialize string to empty data
            
            
            for(int i=0; i < SupL.size(); i++){
            //append data into the result string
            results += (SupL.get(i)).toString();
        }
            
            this.taManSupplierDetails.setText(results);
    }//GEN-LAST:event_btnManViewSupActionPerformed

     
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIMSApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIMSApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIMSApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIMSApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIMSApp().setVisible(true);
            }
        });
        }
   
     
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel belPanel;
    private javax.swing.JButton btnAInvData;
    private javax.swing.JButton btnAStxData;
    private javax.swing.JButton btnASupData;
    private javax.swing.JButton btnClearInv;
    private javax.swing.JButton btnManCLearSup;
    private javax.swing.JButton btnManClearInv;
    private javax.swing.JButton btnManViewInv;
    private javax.swing.JButton btnManViewSup;
    private javax.swing.JButton btnSupClear;
    private javax.swing.JButton btnViewInv;
    private javax.swing.JButton btnViewSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextPane taInventoryDetails;
    private javax.swing.JTextArea taManInventoryDetails;
    private javax.swing.JTextArea taManSupplierDetails;
    private javax.swing.JTextArea taSupplierDetails;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtAInvCat;
    private javax.swing.JTextField txtAInvID;
    private javax.swing.JTextField txtAInvName;
    private javax.swing.JTextField txtAInvQ;
    private javax.swing.JTextField txtAInvRL;
    private javax.swing.JTextField txtAInvSL;
    private javax.swing.JTextField txtAInvUC;
    private javax.swing.JTextField txtStxDate;
    private javax.swing.JTextField txtStxEmployeeAddedBy;
    private javax.swing.JTextField txtStxID;
    private javax.swing.JTextField txtStxItem;
    private javax.swing.JTextField txtStxTotal;
    private javax.swing.JTextField txtSupContact;
    private javax.swing.JTextField txtSupCredit;
    private javax.swing.JTextField txtSupID;
    private javax.swing.JTextField txtSupName;
    // End of variables declaration//GEN-END:variables
}
